"""add media metadata

Revision ID: 27ca3dfc0748
Revises: 9e32e6e2a655
Create Date: 2026-09-08 08:38:12.735872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27ca3dfc0748'
down_revision: Union[str, Sequence[str], None] = '9e32e6e2a655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('duration', sa.Float(), nullable=True))
    op.add_column('media', sa.Column('width', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('media', sa.Column('video_codec', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('audio_codec', sa.String(length=50), nullable=True))
    op.add_column('media', sa.Column('fps', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'fps')
    op.drop_column('media', 'audio_codec')
    op.drop_column('media', 'video_codec')
    op.drop_column('media', 'height')
    op.drop_column('media', 'width')
    op.drop_column('media', 'duration')
    # ### end Alembic commands ###
