"""add project to media

Revision ID: e4395cb07e92
Revises: 5380c313cc8d
Create Date: 2026-09-07 21:54:31.055802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4395cb07e92'
down_revision: Union[str, Sequence[str], None] = '5380c313cc8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('project_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_media_project_id'), 'media', ['project_id'], unique=False)
    op.create_foreign_key('fk_media_project_id_projects', 'media', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Databases created before this constraint was named have PostgreSQL's
    # generated name instead.
    inspector = sa.inspect(op.get_bind())
    names = {
        constraint["name"]
        for constraint in inspector.get_foreign_keys("media")
        if constraint["referred_table"] == "projects"
    }
    for name in ("fk_media_project_id_projects", "media_project_id_fkey"):
        if name in names:
            op.drop_constraint(name, 'media', type_='foreignkey')
    op.drop_index(op.f('ix_media_project_id'), table_name='media')
    op.drop_column('media', 'project_id')
    # ### end Alembic commands ###
